/* ============================================
   Currency Conversion Service
   ============================================ */

const FALLBACK_RATES: Record<string, number> = {
  USD: 1,
  EUR: 0.92,
  GBP: 0.79,
  JPY: 149.5,
  AUD: 1.53,
  CAD: 1.36,
  CHF: 0.88,
  CNY: 7.24,
  INR: 83.1,
  MXN: 17.1,
  BRL: 4.97,
  ZAR: 18.9,
  KRW: 1330,
  SGD: 1.34,
  HKD: 7.82,
  NZD: 1.64,
  SEK: 10.4,
  NOK: 10.6,
  DKK: 6.88,
  PLN: 4.01,
  THB: 35.2,
  VND: 24300,
  IDR: 15600,
  MYR: 4.72,
  PHP: 55.8,
  EGP: 30.9,
  TRY: 30.5,
  AED: 3.67,
  SAR: 3.75,
  QAR: 3.64,
  KWD: 0.307,
  MAD: 10.1,
  TND: 3.12,
  NGN: 905,
  KES: 157,
  GHS: 12.5,
  PKR: 278,
  BDT: 109.5,
  LKR: 312,
  RUB: 91.5,
  UAH: 38.2,
  HUF: 358,
  CZK: 23.2,
  RON: 4.6,
  BGN: 1.79,
  HRK: 6.9,
  ILS: 3.67,
  CLP: 930,
  COP: 3920,
  PEN: 3.72,
  ARS: 850,
  UYU: 39.2,
  DOP: 58.5,
  GTQ: 7.82,
  HNL: 24.6,
  NIO: 36.5,
  PYG: 7260,
  VES: 36.1,
  BOB: 6.91,
  XOF: 603,
  XAF: 603,
  GNF: 8550,
  MZN: 63.5,
  AOA: 830,
  ZMW: 25.8,
  MWK: 1680,
  RWF: 1290,
  BIF: 2850,
  UGX: 3820,
  TZS: 2520,
  ETB: 56.8,
  SDG: 600,
  SSP: 1300,
  SOS: 571,
  DJF: 178,
  ERN: 15,
  LYD: 4.82,
  DZD: 134,
  MRU: 39.6,
  CVE: 101,
  STN: 22.3,
  SCR: 13.5,
  MUR: 46.5,
  MGA: 4580,
  KMF: 452,
  CDF: 2700,
  FKP: 0.79,
  GIP: 0.79,
  SHP: 0.79,
  GGP: 0.79,
  JEP: 0.79,
  IMP: 0.79,
  TTD: 6.76,
  BBD: 2,
  BZD: 2,
  XCD: 2.7,
  HTG: 131.5,
  JMD: 155.5,
  KYD: 0.83,
  ANG: 1.79,
  AWG: 1.79,
  BMD: 1,
  BSD: 1,
  CUC: 1,
  PAB: 1,
  SRD: 35.5,
  TVD: 1.53,
  WST: 2.74,
};

export function convertCurrency(amount: number, from: string, to: string): number {
  if (from === to) return amount;
  const fromRate = FALLBACK_RATES[from.toUpperCase()] ?? 1;
  const toRate = FALLBACK_RATES[to.toUpperCase()] ?? 1;
  return (amount / fromRate) * toRate;
}

export function formatCurrency(amount: number, currency: string): string {
  const noDecimalCurrencies = ["JPY", "KRW", "VND", "IDR", "GNF", "MGA", "KMF", "CDF", "PYG", "CLP", "RWF", "BIF", "UGX", "TZS", "MWK", "LAK", "MMK"];
  const decimals = noDecimalCurrencies.includes(currency.toUpperCase()) ? 0 : 2;
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: currency.toUpperCase(),
    minimumFractionDigits: decimals,
    maximumFractionDigits: decimals,
  }).format(amount);
}

export function getLocalCurrency(countryCode: string): string {
  const mapping: Record<string, string> = {
    US: "USD", GB: "GBP", EU: "EUR", JP: "JPY", AU: "AUD", CA: "CAD",
    CN: "CNY", IN: "INR", BR: "BRL", MX: "MXN", ZA: "ZAR", KR: "KRW",
    SG: "SGD", HK: "HKD", NZ: "NZD", SE: "SEK", NO: "NOK", DK: "DKK",
    PL: "PLN", TH: "THB", VN: "VND", ID: "IDR", MY: "MYR", PH: "PHP",
    EG: "EGP", TR: "TRY", AE: "AED", SA: "SAR", QA: "QAR", KW: "KWD",
    MA: "MAD", TN: "TND", NG: "NGN", KE: "KES", GH: "GHS", PK: "PKR",
    BD: "BDT", LK: "LKR", RU: "RUB", UA: "UAH", HUF: "HUF", CZ: "CZK",
    RO: "RON", BG: "BGN", HR: "HRK", IL: "ILS", CL: "CLP", CO: "COP",
    PE: "PEN", AR: "ARS", UY: "UYU", DO: "DOP", GT: "GTQ", HN: "HNL",
    NI: "NIO", PY: "PYG", BO: "BOB", ZM: "ZMW", DZ: "DZD", LY: "LYD",
    SD: "SDG", ET: "ETB", UG: "UGX", TZ: "TZS", RW: "RWF", BI: "BIF",
    MW: "MWK", MZ: "MZN", AO: "AOA", ZW: "ZWL", NA: "NAD", BW: "BWP",
    SZ: "SZL", LS: "LSL", MG: "MGA", MU: "MUR", SC: "SCR", KM: "KMF",
    CD: "CDF", GA: "XAF", CM: "XAF", CG: "XAF", CF: "XAF", TD: "XAF",
    GQ: "XAF", SN: "XOF", CI: "XOF", ML: "XOF", BF: "XOF", TG: "XOF",
    BJ: "XOF", NE: "XOF", GW: "XOF", MR: "MRU", GN: "GNF", SL: "SLL",
    LR: "LRD", GM: "GMD", CV: "CVE", ST: "STN",
  };
  return mapping[countryCode.toUpperCase()] ?? "USD";
}

export function getAllCurrencies(): { code: string; name: string; symbol: string }[] {
  return [
    { code: "USD", name: "US Dollar", symbol: "$" },
    { code: "EUR", name: "Euro", symbol: "€" },
    { code: "GBP", name: "British Pound", symbol: "£" },
    { code: "JPY", name: "Japanese Yen", symbol: "¥" },
    { code: "AUD", name: "Australian Dollar", symbol: "A$" },
    { code: "CAD", name: "Canadian Dollar", symbol: "C$" },
    { code: "CHF", name: "Swiss Franc", symbol: "Fr" },
    { code: "CNY", name: "Chinese Yuan", symbol: "¥" },
    { code: "INR", name: "Indian Rupee", symbol: "₹" },
    { code: "MXN", name: "Mexican Peso", symbol: "$" },
    { code: "BRL", name: "Brazilian Real", symbol: "R$" },
    { code: "ZAR", name: "South African Rand", symbol: "R" },
    { code: "KRW", name: "South Korean Won", symbol: "₩" },
    { code: "SGD", name: "Singapore Dollar", symbol: "S$" },
    { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$" },
    { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$" },
    { code: "SEK", name: "Swedish Krona", symbol: "kr" },
    { code: "NOK", name: "Norwegian Krone", symbol: "kr" },
    { code: "DKK", name: "Danish Krone", symbol: "kr" },
    { code: "PLN", name: "Polish Zloty", symbol: "zł" },
    { code: "THB", name: "Thai Baht", symbol: "฿" },
    { code: "VND", name: "Vietnamese Dong", symbol: "₫" },
    { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp" },
    { code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
    { code: "PHP", name: "Philippine Peso", symbol: "₱" },
    { code: "EGP", name: "Egyptian Pound", symbol: "E£" },
    { code: "TRY", name: "Turkish Lira", symbol: "₺" },
    { code: "AED", name: "UAE Dirham", symbol: "د.إ" },
    { code: "SAR", name: "Saudi Riyal", symbol: "﷼" },
    { code: "QAR", name: "Qatari Riyal", symbol: "﷼" },
    { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك" },
    { code: "MAD", name: "Moroccan Dirham", symbol: "د.م." },
    { code: "TND", name: "Tunisian Dinar", symbol: "د.ت" },
    { code: "NGN", name: "Nigerian Naira", symbol: "₦" },
    { code: "KES", name: "Kenyan Shilling", symbol: "KSh" },
    { code: "GHS", name: "Ghanaian Cedi", symbol: "₵" },
    { code: "PKR", name: "Pakistani Rupee", symbol: "₨" },
    { code: "BDT", name: "Bangladeshi Taka", symbol: "৳" },
    { code: "LKR", name: "Sri Lankan Rupee", symbol: "Rs" },
    { code: "RUB", name: "Russian Ruble", symbol: "₽" },
    { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴" },
    { code: "HUF", name: "Hungarian Forint", symbol: "Ft" },
    { code: "CZK", name: "Czech Koruna", symbol: "Kč" },
    { code: "RON", name: "Romanian Leu", symbol: "lei" },
    { code: "BGN", name: "Bulgarian Lev", symbol: "лв" },
    { code: "HRK", name: "Croatian Kuna", symbol: "kn" },
    { code: "ILS", name: "Israeli Shekel", symbol: "₪" },
    { code: "CLP", name: "Chilean Peso", symbol: "$" },
    { code: "COP", name: "Colombian Peso", symbol: "$" },
    { code: "PEN", name: "Peruvian Sol", symbol: "S/" },
    { code: "ARS", name: "Argentine Peso", symbol: "$" },
    { code: "UYU", name: "Uruguayan Peso", symbol: "$U" },
    { code: "DOP", name: "Dominican Peso", symbol: "RD$" },
    { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q" },
    { code: "HNL", name: "Honduran Lempira", symbol: "L" },
    { code: "NIO", name: "Nicaraguan Cordoba", symbol: "C$" },
    { code: "PYG", name: "Paraguayan Guarani", symbol: "₲" },
    { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs" },
    { code: "ZMW", name: "Zambian Kwacha", symbol: "K" },
    { code: "DZD", name: "Algerian Dinar", symbol: "د.ج" },
    { code: "LYD", name: "Libyan Dinar", symbol: "ل.د" },
    { code: "SDG", name: "Sudanese Pound", symbol: "ج.س." },
    { code: "ETB", name: "Ethiopian Birr", symbol: "Br" },
    { code: "UGX", name: "Ugandan Shilling", symbol: "USh" },
    { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh" },
    { code: "RWF", name: "Rwandan Franc", symbol: "FRw" },
    { code: "BIF", name: "Burundian Franc", symbol: "FBu" },
    { code: "MWK", name: "Malawian Kwacha", symbol: "MK" },
    { code: "MZN", name: "Mozambican Metical", symbol: "MT" },
    { code: "AOA", name: "Angolan Kwanza", symbol: "Kz" },
    { code: "XOF", name: "West African CFA", symbol: "Fr" },
    { code: "XAF", name: "Central African CFA", symbol: "Fr" },
    { code: "GNF", name: "Guinean Franc", symbol: "Fr" },
    { code: "MGA", name: "Malagasy Ariary", symbol: "Ar" },
    { code: "MUR", name: "Mauritian Rupee", symbol: "₨" },
    { code: "SCR", name: "Seychellois Rupee", symbol: "₨" },
    { code: "KMF", name: "Comorian Franc", symbol: "Fr" },
    { code: "CDF", name: "Congolese Franc", symbol: "FC" },
    { code: "CVE", name: "Cape Verdean Escudo", symbol: "$" },
    { code: "STN", name: "Sao Tome Dobra", symbol: "Db" },
    { code: "LRD", name: "Liberian Dollar", symbol: "$" },
    { code: "GMD", name: "Gambian Dalasi", symbol: "D" },
    { code: "SLL", name: "Sierra Leonean Leone", symbol: "Le" },
    { code: "MRU", name: "Mauritanian Ouguiya", symbol: "UM" },
    { code: "KPW", name: "North Korean Won", symbol: "₩" },
    { code: "TWD", name: "Taiwan Dollar", symbol: "NT$" },
    { code: "MMK", name: "Myanmar Kyat", symbol: "Ks" },
    { code: "KHR", name: "Cambodian Riel", symbol: "៛" },
    { code: "LAK", name: "Lao Kip", symbol: "₭" },
    { code: "BND", name: "Brunei Dollar", symbol: "B$" },
    { code: "FJD", name: "Fijian Dollar", symbol: "$" },
    { code: "PGK", name: "Papua New Guinean Kina", symbol: "K" },
    { code: "SBD", name: "Solomon Islands Dollar", symbol: "$" },
    { code: "TOP", name: "Tongan Pa'anga", symbol: "T$" },
    { code: "VUV", name: "Vanuatu Vatu", symbol: "Vt" },
    { code: "WST", name: "Samoan Tala", symbol: "T" },
    { code: "BWP", name: "Botswana Pula", symbol: "P" },
    { code: "NAD", name: "Namibian Dollar", symbol: "$" },
    { code: "SZL", name: "Swazi Lilangeni", symbol: "E" },
    { code: "LSL", name: "Lesotho Loti", symbol: "L" },
  ];
}
